name: arcade_storage
description: Storage for Arcade
version: 1.2.1
repository: https://github.com/dartarcade/arcade/tree/main/packages/arcade_storage
issue_tracker: https://github.com/dartarcade/arcade/issues
resolution: workspace

environment:
  sdk: ^3.5.0

dev_dependencies:
  lint: ^2.8.0
  test: ^1.26.2

