name: arcade_cache_redis
description: Redis cache for Arcade
version: 1.1.1
repository: https://github.com/dartarcade/arcade/tree/main/packages/arcade_cache_redis
issue_tracker: https://github.com/dartarcade/arcade/issues
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  arcade_cache: ^1.1.1
  redis: ^4.0.0
dev_dependencies:
  lint: ^2.8.0
  test: ^1.26.0
