name: arcade_logger
description: A logger for Arcade
version: 1.2.1
repository: https://github.com/dartarcade/arcade/tree/main/packages/arcade_logger
issue_tracker: https://github.com/dartarcade/arcade/issues
resolution: workspace

environment:
  sdk: ^3.8.3

dependencies:
  ansi_styles: ^0.3.2+1
  arcade_config: ^1.2.1

dev_dependencies:
  lint: ^2.8.0
  test: ^1.26.2
