name: arcade_example
description: A sample app showing how to use arcade.
version: 1.0.1
repository: https://github.com/dartarcade/arcade/tree/main/packages/arcade/example
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  arcade:
    path: ..
  arcade_logger: ^1.2.1
  json_annotation: ^4.8.1
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  lint: ^2.1.2
  test: ^1.21.0
issue_tracker: https://github.com/dartarcade/arcade/issues
resolution: workspace
