name: todo_api
description: Starter Arcade application using recommended code generation libraries
version: 2.2.0
publish_to: none
repository: https://github.com/dartarcade/arcade/tree/main/samples/todo_api
issue_tracker: https://github.com/dartarcade/arcade/issues
resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  arcade: ^1.1.1
  arcade_swagger: ^1.1.1
  dart_jsonwebtoken: ^3.2.0
  drift: ^2.27.0
  drift_postgres: ^1.3.1
  envied: ^1.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  hashlib: ^2.0.0
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  luthor: '>=0.13.1 <1.0.0'
  postgres: ^3.5.6
  superclass: ^0.6.0

dev_dependencies:
  build_runner: ^2.5.4
  drift_dev: ^2.27.0
  envied_generator: ^1.1.1
  freezed: ^3.0.6
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  lint: ^2.8.0
  luthor_generator: '>=0.13.1 <1.0.0'
  superclass_generator: ^0.6.0
