name: Code Quality

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: ['stable', '3.8.3']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install DPK
        run: dart pub global activate dpk
      - name: Run dpk get
        run: dpk get
      - name: Run code generation on example app
        run: dpk run example:build
      - name: Analyze
        run: dpk run analyze
  
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sdk: ['stable', '3.8.3']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install DPK
        run: dart pub global activate dpk
      - name: Run dpk get
        run: dpk get
      - name: Format
        run: dpk run format
